name: Azure Infrastructure Deployment Demo

on:
  workflow_dispatch:

env:
  resourceGroup: demo-resource-gp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code including the Bicep file
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        id: deploy_bicep
        with:
          scope: resource-group
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.resourceGroup }}
          template: ./azuredeploy.bicep
          parameters: ./azuredeploy.bicepparam
          deploymentName: bicep_infrastructure_deployment

